### ISSUE TITLE
BPM wrong

### ISSUE THREAD

**Issue by JoelFNF** [Sonamaker1/ThisEngine-FNF#4]
cannot get bpm right on my mod. on kade engine i can. pls help.

**Comment by Sonamaker1** [comment]
Hm, I'm sorry to hear that but I need some more information. Could you provide a video of the chart? Or the chart itself so I can test it?

**Comment by Sonamaker1** [comment]
Can’t reproduce error so closing this now

**Comment by Sonamaker1** [comment]
Can’t reproduce error so closing this now
